//****************************************************************************//
// System           : HSS100                                                  //
// Sub System       : HVersion                                                //
// Program name     : Hバージョン                                             //
//                  : HVersion.pas                                            //
// Name Space       :                                                         //
// Programmer       : Kumagai                                                 //
// Date             : 2009.08.10                                              //
// Note             : HSS70から生成                                           //
//                  : High Speed Specialコンポ バージョン管理のファイル       //
//----------------------------------------------------------------------------//
// Update Note      :                                                         //
//----------------------------------------------------------------------------//
//          (c)Copyright  2009 Broadleaf Co,. Ltd                             //
//****************************************************************************//
unit HVersion;
{$R-}

interface

//*************************************************//
//  Version 定数の設定                             //
//*************************************************//

type
  TVersion = String;

//========== ArrowKeyControl
const HArrowKeyControlVersion = 'HSS10.00';

//========== RetKeyControl
const HRetKeyControlVersion = 'HSS10.00';

//========== HEdit
const HEditVersion = 'HSS10.00';

//========== HNedit
const HNeditVersion = 'HSS10.00';

//========== HDateEdit
const HDateEditVersion = 'HSS10.00';

//========== HLine
const HLineVersion = 'HSS10.00';

//========== HDoubleCaptionButton
const HDoubleCaptionButtonVersion = 'HSS10.00';

//========== HMemoryPositionVersion
const HMemPosVersion = 'HSS10.00';

//========== HLabel
const HLabelVersion = 'HSS10.00';

//========== HFrameControl
const HFrameControlVersion = 'HSS10.00';

//========== HGradationImageVersion
const HGradationImageVersion = 'HSS10.00';

//========== HRepeatImageVersion
const HRepeatImageVersion = 'HSS10.00';

//========== HDllCallVersion
const HDllCallVersion = 'HSS10.00';

//========== HComboBoxVersion
const HComboBoxVersion = 'HSS10.00';

//========== HHelpSocketVersion
const HHelpSocketVersion = 'HSS10.00';

//========== HCheckListBoxVersion
const HCheckListBoxVersion = 'HSS10.00';

//========== HShrParaVersion
const HShrParaVersion = 'HSS10.00';

//========== HRscCtlVersion
const HRscCtlVersion = 'HSS10.00';

//========== HFuncKey
const HFuncKeyVersion = 'HSS10.00';

//========== HSpeedExtButton
const HSpeedExtButtonVersion = 'HSS10.00';

//========== HADOACS
const HADOACSVersion = 'HSS10.00';

//========== HGrid
const HGridVersion = 'HSS10.00';

implementation

end.

