using System.IO;
using System.Text;

namespace Broadleaf.Application.Remoting
{
    /// <summary>
    /// 拠点コード変換対象設定リスト
    /// </summary>
    /// <remarks>
    /// <br>Update Note : 2018/07/25 呉軍</br>
    /// <br>管理番号    : 11400935-00</br>
    /// <br>            : Redmine#49726 拠点コード変換対象テーブルとカラムの追加</br>
    /// </remarks>
    public static class XMLSectionConvertList
    {
        #region convertList
        public static string convertList = @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<ArrayOfSectionConvertList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
	<SectionConvertList>
		<TargetTable>SECINFOSETRF</TargetTable>
		<TargetTableName>拠点情報設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUBSECTIONRF</TargetTable>
		<TargetTableName>部門マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>WAREHOUSERF</TargetTable>
		<TargetTableName>倉庫マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>EMPLOYEERF</TargetTable>
		<TargetTableName>従業員マスタ</TargetTableName>
		<TargetColumn>BELONGSECTIONCODERF</TargetColumn>
		<TargetColumnName>所属拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ALLDEFSETRF</TargetTable>
		<TargetTableName>全体初期値設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>NOMNGSETRF</TargetTable>
		<TargetTableName>番号管理設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>HOLIDAYSETTINGRF</TargetTable>
		<TargetTableName>休業日設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ESTIMATEDEFSETRF</TargetTable>
		<TargetTableName>見積初期値設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ACPTANODRTTLSTRF</TargetTable>
		<TargetTableName>受発注管理全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESTTLSTRF</TargetTable>
		<TargetTableName>売上全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>BILLALLSTRF</TargetTable>
		<TargetTableName>請求全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTDMDSETRF</TargetTable>
		<TargetTableName>得意先マスタ（請求書管理）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKTTLSTRF</TargetTable>
		<TargetTableName>仕入在庫全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKMNGTTLSTRF</TargetTable>
		<TargetTableName>在庫管理全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTSLIPMNGRF</TargetTable>
		<TargetTableName>得意先マスタ（伝票管理）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PRTOUTSETRF</TargetTable>
		<TargetTableName>帳票出力設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>RATEPROTYMNGRF</TargetTable>
		<TargetTableName>掛率優先管理マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ISOLISLANDPRCRF</TargetTable>
		<TargetTableName>離島価格マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>RATERF</TargetTable>
		<TargetTableName>掛率マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>EMPSALESTARGETRF</TargetTable>
		<TargetTableName>従業員別売上目標設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTSALESTARGETRF</TargetTable>
		<TargetTableName>得意先別売上目標設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>GCDSALESTARGETRF</TargetTable>
		<TargetTableName>商品別売上目標設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>MNGSECTIONCODERF</TargetColumn>
		<TargetColumnName>管理拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>INPSECTIONCODERF</TargetColumn>
		<TargetColumnName>入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>CLAIMSECTIONCODERF</TargetColumn>
		<TargetColumnName>請求拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUMCUSTSTRF</TargetTable>
		<TargetTableName>得意先マスタ（総括設定）</TargetTableName>
		<TargetColumn>DEMANDADDUPSECCDRF</TargetColumn>
		<TargetColumnName>請求計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPPLIERRF</TargetTable>
		<TargetTableName>仕入先マスタ</TargetTableName>
		<TargetColumn>MNGSECTIONCODERF</TargetColumn>
		<TargetColumnName>管理拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPPLIERRF</TargetTable>
		<TargetTableName>仕入先マスタ</TargetTableName>
		<TargetColumn>INPSECTIONCODERF</TargetColumn>
		<TargetColumnName>入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPPLIERRF</TargetTable>
		<TargetTableName>仕入先マスタ</TargetTableName>
		<TargetColumn>PAYMENTSECTIONCODERF</TargetColumn>
		<TargetColumnName>支払拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>GOODSMNGRF</TargetTable>
		<TargetTableName>商品管理情報マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>BLCODEGUIDERF</TargetTable>
		<TargetTableName>BLコードガイドマスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKRF</TargetTable>
		<TargetTableName>在庫マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PARTSPOSCODEURF</TargetTable>
		<TargetTableName>部位コードマスタ（ユーザー登録）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PRMSETTINGURF</TargetTable>
		<TargetTableName>優良設定マスタ（ユーザー登録分）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>UOESETTINGRF</TargetTable>
		<TargetTableName>UOE自社設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>UOEGUIDENAMERF</TargetTable>
		<TargetTableName>UOEガイド名称マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>UOESUPPLIERRF</TargetTable>
		<TargetTableName>UOE発注先マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SANDESETTINGRF</TargetTable>
		<TargetTableName>オートバックス設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>SALESINPSECCDRF</TargetColumn>
		<TargetColumnName>売上入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>DEMANDADDUPSECCDRF</TargetColumn>
		<TargetColumnName>請求計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>RESULTSADDUPSECCDRF</TargetColumn>
		<TargetColumnName>実績計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>UPDATESECCDRF</TargetColumn>
		<TargetColumnName>更新拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESDETAILRF</TargetTable>
		<TargetTableName>売上明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESDETAILRF</TargetTable>
		<TargetTableName>売上明細データ</TargetTableName>
		<TargetColumn>RATESECTPRICEUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（定価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESDETAILRF</TargetTable>
		<TargetTableName>売上明細データ</TargetTableName>
		<TargetColumn>RATESECTSALUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（売上単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESDETAILRF</TargetTable>
		<TargetTableName>売上明細データ</TargetTableName>
		<TargetColumn>RATESECTCSTUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（原価単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>SALESINPSECCDRF</TargetColumn>
		<TargetColumnName>売上入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>DEMANDADDUPSECCDRF</TargetColumn>
		<TargetColumnName>請求計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>RESULTSADDUPSECCDRF</TargetColumn>
		<TargetColumnName>実績計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>UPDATESECCDRF</TargetColumn>
		<TargetColumnName>更新拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTDTLRF</TargetTable>
		<TargetTableName>売上履歴明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTDTLRF</TargetTable>
		<TargetTableName>売上履歴明細データ</TargetTableName>
		<TargetColumn>RATESECTPRICEUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（定価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTDTLRF</TargetTable>
		<TargetTableName>売上履歴明細データ</TargetTableName>
		<TargetColumn>RATESECTSALUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（売上単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALESHISTDTLRF</TargetTable>
		<TargetTableName>売上履歴明細データ</TargetTableName>
		<TargetColumn>RATESECTCSTUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（原価単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ACCEPTODRRF</TargetTable>
		<TargetTableName>受注マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>INPUTDEPOSITSECCDRF</TargetColumn>
		<TargetColumnName>入金入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>UPDATESECCDRF</TargetColumn>
		<TargetColumnName>更新拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DEPOSITALWRF</TargetTable>
		<TargetTableName>入金引当マスタ</TargetTableName>
		<TargetColumn>INPUTDEPOSITSECCDRF</TargetColumn>
		<TargetColumnName>入金入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DEPOSITALWRF</TargetTable>
		<TargetTableName>入金引当マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPRF</TargetTable>
		<TargetTableName>仕入データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPRF</TargetTable>
		<TargetTableName>仕入データ</TargetTableName>
		<TargetColumn>STOCKSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPRF</TargetTable>
		<TargetTableName>仕入データ</TargetTableName>
		<TargetColumn>STOCKADDUPSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKDETAILRF</TargetTable>
		<TargetTableName>仕入明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKDETAILRF</TargetTable>
		<TargetTableName>仕入明細データ</TargetTableName>
		<TargetColumn>RATESECTSTCKUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（仕入単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPHISTRF</TargetTable>
		<TargetTableName>仕入履歴データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPHISTRF</TargetTable>
		<TargetTableName>仕入履歴データ</TargetTableName>
		<TargetColumn>STOCKSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLIPHISTRF</TargetTable>
		<TargetTableName>仕入履歴データ</TargetTableName>
		<TargetColumn>STOCKADDUPSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLHISTDTLRF</TargetTable>
		<TargetTableName>仕入履歴明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKSLHISTDTLRF</TargetTable>
		<TargetTableName>仕入履歴明細データ</TargetTableName>
		<TargetColumn>RATESECTSTCKUNPRCRF</TargetColumn>
		<TargetColumnName>掛率設定拠点（仕入単価）</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYMENTSLPRF</TargetTable>
		<TargetTableName>支払伝票マスタ</TargetTableName>
		<TargetColumn>PAYMENTINPSECTIONCDRF</TargetColumn>
		<TargetColumnName>支払入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYMENTSLPRF</TargetTable>
		<TargetTableName>支払伝票マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYMENTSLPRF</TargetTable>
		<TargetTableName>支払伝票マスタ</TargetTableName>
		<TargetColumn>UPDATESECCDRF</TargetColumn>
		<TargetColumnName>更新拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKMOVERF</TargetTable>
		<TargetTableName>在庫移動データ</TargetTableName>
		<TargetColumn>UPDATESECCDRF</TargetColumn>
		<TargetColumnName>更新拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKMOVERF</TargetTable>
		<TargetTableName>在庫移動データ</TargetTableName>
		<TargetColumn>BFSECTIONCODERF</TargetColumn>
		<TargetColumnName>移動元拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKMOVERF</TargetTable>
		<TargetTableName>在庫移動データ</TargetTableName>
		<TargetColumn>AFSECTIONCODERF</TargetColumn>
		<TargetColumnName>移動先拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKADJUSTRF</TargetTable>
		<TargetTableName>在庫調整データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKADJUSTRF</TargetTable>
		<TargetTableName>在庫調整データ</TargetTableName>
		<TargetColumn>STOCKSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKADJUSTDTLRF</TargetTable>
		<TargetTableName>在庫調整明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKACPAYHISTRF</TargetTable>
		<TargetTableName>在庫受払履歴データ</TargetTableName>
		<TargetColumn>INPUTSECTIONCDRF</TargetColumn>
		<TargetColumnName>入力拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKACPAYHISTRF</TargetTable>
		<TargetTableName>在庫受払履歴データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKACPAYHISTRF</TargetTable>
		<TargetTableName>在庫受払履歴データ</TargetTableName>
		<TargetColumn>BFSECTIONCODERF</TargetColumn>
		<TargetColumnName>移動元拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKACPAYHISTRF</TargetTable>
		<TargetTableName>在庫受払履歴データ</TargetTableName>
		<TargetColumn>AFSECTIONCODERF</TargetColumn>
		<TargetColumnName>移動先拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>STOCKHISTORYRF</TargetTable>
		<TargetTableName>在庫履歴データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTDMDPRCRF</TargetTable>
		<TargetTableName>得意先請求金額マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTDMDPRCRF</TargetTable>
		<TargetTableName>得意先請求金額マスタ</TargetTableName>
		<TargetColumn>RESULTSSECTCDRF</TargetColumn>
		<TargetColumnName>実績拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DMDDEPOTOTALRF</TargetTable>
		<TargetTableName>請求入金集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CUSTACCRECRF</TargetTable>
		<TargetTableName>得意先売掛金額マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ACCRECDEPOTOTALRF</TargetTable>
		<TargetTableName>売掛入金集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPLIERPAYRF</TargetTable>
		<TargetTableName>仕入先支払金額マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPLIERPAYRF</TargetTable>
		<TargetTableName>仕入先支払金額マスタ</TargetTableName>
		<TargetColumn>RESULTSSECTCDRF</TargetColumn>
		<TargetColumnName>実績拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ACCPAYTOTALRF</TargetTable>
		<TargetTableName>精算支払集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUPLACCPAYRF</TargetTable>
		<TargetTableName>仕入先買掛金額マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>ACALCPAYTOTALRF</TargetTable>
		<TargetTableName>買掛支払集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DMDCADDUPHISRF</TargetTable>
		<TargetTableName>請求締更新履歴マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYMENTADDUPHISRF</TargetTable>
		<TargetTableName>支払締更新履歴マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>MONTHLYADDUPHISRF</TargetTable>
		<TargetTableName>月次締更新履歴マスタ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CNVCARPARTSRF</TargetTable>
		<TargetTableName>車輌部品データ（コンバート）</TargetTableName>
		<TargetColumn>RESULTSADDUPSECCDRF</TargetColumn>
		<TargetColumnName>実績計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>MTTLSALESSTOCKSLIPRF</TargetTable>
		<TargetTableName>売上仕入月次集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>UOEORDERDTLRF</TargetTable>
		<TargetTableName>UOE発注データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SANDESALSNDLOGRF</TargetTable>
		<TargetTableName>S＆E売上データ送信ログ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>MTTLSTOCKSLIPRF</TargetTable>
		<TargetTableName>仕入月次集計データ</TargetTableName>
		<TargetColumn>STOCKSECTIONCDRF</TargetColumn>
		<TargetColumnName>仕入拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SECMNGEPSETRF</TargetTable>
		<TargetTableName>拠点管理企業設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SECMNGCONNECTSTRF</TargetTable>
		<TargetTableName>拠点管理接続先設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>RCVDRAFTDATARF</TargetTable>
		<TargetTableName>受取手形データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>RCVDRAFTDATARF</TargetTable>
		<TargetTableName>受取手形データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYDRAFTDATARF</TargetTable>
		<TargetTableName>支払手形データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PAYDRAFTDATARF</TargetTable>
		<TargetTableName>支払手形データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CAMPAIGNMNGRF</TargetTable>
		<TargetTableName>キャンペーン管理マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CAMPAIGNPRCPRSTRF</TargetTable>
		<TargetTableName>キャンペーン売価優先設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CAMPAIGNTARGETRF</TargetTable>
		<TargetTableName>キャンペーン目標設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>INVENTDATAPRERF</TargetTable>
		<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>INVENTDATAPRERF</TargetTable>
		<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
		<TargetColumn>MNGSECTIONCODESTRF</TargetColumn>
		<TargetColumnName>管理拠点コード開始</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>INVENTDATAPRERF</TargetTable>
		<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
		<TargetColumn>MNGSECTIONCODEEDRF</TargetColumn>
		<TargetColumnName>管理拠点コード終了</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>INVENTORYDATARF</TargetTable>
		<TargetTableName>棚卸データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>MTTLSALESSLIPRF</TargetTable>
		<TargetTableName>売上月次集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>GOODSMTTLSASLIPRF</TargetTable>
		<TargetTableName>商品別売上月次集計データ</TargetTableName>
		<TargetColumn>ADDUPSECCODERF</TargetColumn>
		<TargetColumnName>計上拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>DATAUPDMNGRF</TargetTable>
		<TargetTableName>ユーザデータ更新管理マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SECMNGSETRF</TargetTable>
		<TargetTableName>拠点管理設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SECMNGSETRF</TargetTable>
		<TargetTableName>拠点管理設定マスタ</TargetTableName>
		<TargetColumn>SENDDESTSECCODERF</TargetColumn>
		<TargetColumnName>送信先拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CAMPAIGNSTRF</TargetTable>
		<TargetTableName>キャンペーン設定マスタ</TargetTableName>
		<TargetColumn>CAMPEXECSECCODERF</TargetColumn>
		<TargetColumnName>キャンペーン実施拠点</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUMSUPPSTRF</TargetTable>
		<TargetTableName>仕入先マスタ（総括設定）</TargetTableName>
		<TargetColumn>SUMSECTIONCDRF</TargetColumn>
		<TargetColumnName>総括拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SUMSUPPSTRF</TargetTable>
		<TargetTableName>仕入先マスタ（総括設定）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>INSPECTTTLSTRF</TargetTable>
		<TargetTableName>検品全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CIRCULINVENTHISDATARF</TargetTable>
		<TargetTableName>循環棚卸履歴データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>CIRCULINVENTHISDTLRF</TargetTable>
		<TargetTableName>循環棚卸履歴明細データ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>EDICOOPERATSTRF</TargetTable>
		<TargetTableName>EDI連携設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>TEXTOUTHISLOGRF</TargetTable>
		<TargetTableName>テキスト出力履歴ログデータ</TargetTableName>
		<TargetColumn>LOGINSECTIONCDRF</TargetColumn>
		<TargetColumnName>ログイン拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>AUTOANSITEMSTRF</TargetTable>
		<TargetTableName>自動回答品目設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>IMPORTANTPRTSTRF</TargetTable>
		<TargetTableName>重点品目設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PCCTTLSTRF</TargetTable>
		<TargetTableName>PCC全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PMOPTMNGRF</TargetTable>
		<TargetTableName>PMオプション管理マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PMTABTTLSTSECRF</TargetTable>
		<TargetTableName>PMTAB全体設定マスタ（拠点別）</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>PMTABUPLDEXCLSVRF</TargetTable>
		<TargetTableName>PMTABアップロード排他制御マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALCPRTCNCTINFRF</TargetTable>
		<TargetTableName>売上連携接続情報マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SALCPRTSNDLOGRF</TargetTable>
		<TargetTableName>売上連携送信ログ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMDELIDATESTRF</TargetTable>
		<TargetTableName>SCM納期設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMNEWARRNTFYSTRF</TargetTable>
		<TargetTableName>SCM新着通知設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMPRIORSTRF</TargetTable>
		<TargetTableName>SCM優先設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMPRTSETTINGRF</TargetTable>
		<TargetTableName>SCM品目設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMTIMEDATARF</TargetTable>
		<TargetTableName>SCM新着データ表示管理</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SCMTTLSTRF</TargetTable>
		<TargetTableName>SCM全体設定マスタ</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
	<SectionConvertList>
		<TargetTable>SYNCSTATEDSPTERMSTRF</TargetTable>
		<TargetTableName>同期状態表示端末設定</TargetTableName>
		<TargetColumn>SECTIONCODERF</TargetColumn>
		<TargetColumnName>拠点コード</TargetColumnName>
	</SectionConvertList>
</ArrayOfSectionConvertList>";
        #endregion
        public static MemoryStream ms()
        {
            return new MemoryStream(Encoding.UTF8.GetBytes(convertList));
        }
    }
}