using System.IO;
using System.Text;

namespace Broadleaf.Application.Remoting
{
    /// <summary>
    /// 得意先コード変換対象設定リスト
    /// </summary>
    /// <remarks>
    /// <br>Update Note : 2018/07/25 呉軍</br>
    /// <br>管理番号    : 11400935-00</br>
    /// <br>            : Redmine#49726 得意先コード変換対象テーブルとカラムの追加</br>
    /// </remarks>
    public static class XMLCustomerConvertList
    {
        #region convertList
        public static string convertList = @"<?xml version=""1.0"" encoding=""utf-8"" standalone=""yes""?>
<ArrayOfCustomerConvertList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
	<CustomerConvertList>
		<TargetTable>WAREHOUSERF</TargetTable>
		<TargetTableName>倉庫マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTDMDSETRF</TargetTable>
		<TargetTableName>得意先マスタ（請求書管理）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTSLIPMNGRF</TargetTable>
		<TargetTableName>得意先マスタ（伝票管理）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>RATERF</TargetTable>
		<TargetTableName>掛率マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTSALESTARGETRF</TargetTable>
		<TargetTableName>得意先別売上目標設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>PRICESELECTSETRF</TargetTable>
		<TargetTableName>標準価格選択設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTOMERCHANGERF</TargetTable>
		<TargetTableName>得意先マスタ（変動情報）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTSLIPNOSETRF</TargetTable>
		<TargetTableName>得意先マスタ（伝票番号）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTRATEGROUPRF</TargetTable>
		<TargetTableName>得意先マスタ（掛率グループ）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SUMCUSTSTRF</TargetTable>
		<TargetTableName>得意先マスタ（総括設定）</TargetTableName>
		<TargetColumn>SUMCLAIMCUSTCODERF</TargetColumn>
		<TargetColumnName>総括請求得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SUMCUSTSTRF</TargetTable>
		<TargetTableName>得意先マスタ（総括設定）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>PARTSPOSCODEURF</TargetTable>
		<TargetTableName>部位コードマスタ（ユーザー登録）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SANDESETTINGRF</TargetTable>
		<TargetTableName>オートバックス設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CAMPAIGNLINKRF</TargetTable>
		<TargetTableName>キャンペーン関連マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CAMPAIGNMNGRF</TargetTable>
		<TargetTableName>キャンペーン管理マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CAMPAIGNTARGETRF</TargetTable>
		<TargetTableName>キャンペーン目標設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>EDICOOPERATSTRF</TargetTable>
		<TargetTableName>EDI連携設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>PCCPRIORSTRF</TargetTable>
		<TargetTableName>PCCUOE優先設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>PMTABTTLSTCUSTRF</TargetTable>
		<TargetTableName>PMTAB全体設定マスタ（得意先別）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SCMACODRDATARF</TargetTable>
		<TargetTableName>SCM受注データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SCMNEWARRNTFYSTRF</TargetTable>
		<TargetTableName>SCM新着通知設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SCMDELIDATESTRF</TargetTable>
		<TargetTableName>SCM納期設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SCMPRTSETTINGRF</TargetTable>
		<TargetTableName>SCM品目設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SCMPRIORSTRF</TargetTable>
		<TargetTableName>SCM優先設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>TSPCPRTRF</TargetTable>
		<TargetTableName>TSP連携マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>UOEORDERDTLRF</TargetTable>
		<TargetTableName>UOE発注データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>STOCKACPAYHISTRF</TargetTable>
		<TargetTableName>在庫受払履歴データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>STOCKDETAILRF</TargetTable>
		<TargetTableName>仕入明細データ</TargetTableName>
		<TargetColumn>SALESCUSTOMERCODERF</TargetColumn>
		<TargetColumnName>販売先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>STOCKSLHISTDTLRF</TargetTable>
		<TargetTableName>仕入履歴明細データ</TargetTableName>
		<TargetColumn>SALESCUSTOMERCODERF</TargetColumn>
		<TargetColumnName>販売先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>AUTOANSITEMSTRF</TargetTable>
		<TargetTableName>自動回答品目設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CARMANAGEMENTRF</TargetTable>
		<TargetTableName>車両管理マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CNVCARPARTSRF</TargetTable>
		<TargetTableName>車輌部品データ（コンバート）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>RCVDRAFTDATARF</TargetTable>
		<TargetTableName>受取手形データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>IMPORTANTPRTSTRF</TargetTable>
		<TargetTableName>重点品目設定マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>GOODSMTTLSASLIPRF</TargetTable>
		<TargetTableName>商品別売上月次集計データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>DMDCADDUPHISRF</TargetTable>
		<TargetTableName>請求締更新履歴マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>DMDDEPOTOTALRF</TargetTable>
		<TargetTableName>請求入金集計データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>DMDDEPOTOTALRF</TargetTable>
		<TargetTableName>請求入金集計データ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>INVENTORYDATARF</TargetTable>
		<TargetTableName>棚卸データ</TargetTableName>
		<TargetColumn>SHIPCUSTOMERCODERF</TargetColumn>
		<TargetColumnName>出荷先得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTOMERMEMORF</TargetTable>
		<TargetTableName>得意先マスタ（メモ情報）</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTDMDPRCRF</TargetTable>
		<TargetTableName>得意先請求金額マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTDMDPRCRF</TargetTable>
		<TargetTableName>得意先請求金額マスタ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTACCRECRF</TargetTable>
		<TargetTableName>得意先売掛金額マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>CUSTACCRECRF</TargetTable>
		<TargetTableName>得意先売掛金額マスタ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>ACCRECDEPOTOTALRF</TargetTable>
		<TargetTableName>売掛入金集計データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>ACCRECDEPOTOTALRF</TargetTable>
		<TargetTableName>売掛入金集計データ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>MTTLSALESSLIPRF</TargetTable>
		<TargetTableName>売上月次集計データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>CLAIMCODERF</TargetColumn>
		<TargetColumnName>請求先コード</TargetColumnName>
	</CustomerConvertList>
	<CustomerConvertList>
		<TargetTable>SALCPRTCNCTINFRF</TargetTable>
		<TargetTableName>売上連携接続情報マスタ</TargetTableName>
		<TargetColumn>CUSTOMERCODERF</TargetColumn>
		<TargetColumnName>得意先コード		</TargetColumnName>
	</CustomerConvertList>
</ArrayOfCustomerConvertList>";
        #endregion
        public static MemoryStream ms()
        {
            return new MemoryStream(Encoding.UTF8.GetBytes(convertList));
        }
    }
}