//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Broadleaf.Application.Controller {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("CampaignMngDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class CampaignMngDataSet : global::System.Data.DataSet {
        
        private CampaignMngDataTable tableCampaignMng;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CampaignMngDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected CampaignMngDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["CampaignMng"] != null)) {
                    base.Tables.Add(new CampaignMngDataTable(ds.Tables["CampaignMng"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CampaignMngDataTable CampaignMng {
            get {
                return this.tableCampaignMng;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            CampaignMngDataSet cln = ((CampaignMngDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["CampaignMng"] != null)) {
                    base.Tables.Add(new CampaignMngDataTable(ds.Tables["CampaignMng"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableCampaignMng = ((CampaignMngDataTable)(base.Tables["CampaignMng"]));
            if ((initTable == true)) {
                if ((this.tableCampaignMng != null)) {
                    this.tableCampaignMng.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "CampaignMngDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/CampaignMngDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCampaignMng = new CampaignMngDataTable();
            base.Tables.Add(this.tableCampaignMng);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCampaignMng() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            CampaignMngDataSet ds = new CampaignMngDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void CampaignMngRowChangeEventHandler(object sender, CampaignMngRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CampaignMngDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnRowNo;
            
            private global::System.Data.DataColumn columnUpdateTime;
            
            private global::System.Data.DataColumn columnCampaignCode;
            
            private global::System.Data.DataColumn columnCampaignName;
            
            private global::System.Data.DataColumn columnSectionCode;
            
            private global::System.Data.DataColumn columnCampaignSettingKind;
            
            private global::System.Data.DataColumn columnGoodsMakerCode;
            
            private global::System.Data.DataColumn columnGoodsMakerName;
            
            private global::System.Data.DataColumn columnGoodsNo;
            
            private global::System.Data.DataColumn columnBLGoodsCode;
            
            private global::System.Data.DataColumn columnGoodsName;
            
            private global::System.Data.DataColumn columnBLGroupCode;
            
            private global::System.Data.DataColumn columnSalesCode;
            
            private global::System.Data.DataColumn columnSalesPriceSetDiv;
            
            private global::System.Data.DataColumn columnCustomerCode;
            
            private global::System.Data.DataColumn columnDiscountRate;
            
            private global::System.Data.DataColumn columnRateVal;
            
            private global::System.Data.DataColumn columnPriceFl;
            
            private global::System.Data.DataColumn columnPriceStartDate;
            
            private global::System.Data.DataColumn columnPriceEndDate;
            
            private global::System.Data.DataColumn columnFilterGuid;
            
            private global::System.Data.DataColumn columnRowDeleteFlg;
            
            private global::System.Data.DataColumn columnUpdateTime2;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngDataTable() {
                this.TableName = "CampaignMng";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CampaignMngDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected CampaignMngDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RowNoColumn {
                get {
                    return this.columnRowNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UpdateTimeColumn {
                get {
                    return this.columnUpdateTime;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CampaignCodeColumn {
                get {
                    return this.columnCampaignCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CampaignNameColumn {
                get {
                    return this.columnCampaignName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SectionCodeColumn {
                get {
                    return this.columnSectionCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CampaignSettingKindColumn {
                get {
                    return this.columnCampaignSettingKind;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoodsMakerCodeColumn {
                get {
                    return this.columnGoodsMakerCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoodsMakerNameColumn {
                get {
                    return this.columnGoodsMakerName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoodsNoColumn {
                get {
                    return this.columnGoodsNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BLGoodsCodeColumn {
                get {
                    return this.columnBLGoodsCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoodsNameColumn {
                get {
                    return this.columnGoodsName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BLGroupCodeColumn {
                get {
                    return this.columnBLGroupCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SalesCodeColumn {
                get {
                    return this.columnSalesCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SalesPriceSetDivColumn {
                get {
                    return this.columnSalesPriceSetDiv;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CustomerCodeColumn {
                get {
                    return this.columnCustomerCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DiscountRateColumn {
                get {
                    return this.columnDiscountRate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RateValColumn {
                get {
                    return this.columnRateVal;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PriceFlColumn {
                get {
                    return this.columnPriceFl;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PriceStartDateColumn {
                get {
                    return this.columnPriceStartDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PriceEndDateColumn {
                get {
                    return this.columnPriceEndDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FilterGuidColumn {
                get {
                    return this.columnFilterGuid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RowDeleteFlgColumn {
                get {
                    return this.columnRowDeleteFlg;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UpdateTime2Column {
                get {
                    return this.columnUpdateTime2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngRow this[int index] {
                get {
                    return ((CampaignMngRow)(this.Rows[index]));
                }
            }
            
            public event CampaignMngRowChangeEventHandler CampaignMngRowChanging;
            
            public event CampaignMngRowChangeEventHandler CampaignMngRowChanged;
            
            public event CampaignMngRowChangeEventHandler CampaignMngRowDeleting;
            
            public event CampaignMngRowChangeEventHandler CampaignMngRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCampaignMngRow(CampaignMngRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngRow AddCampaignMngRow(
                        int RowNo, 
                        string UpdateTime, 
                        int CampaignCode, 
                        string CampaignName, 
                        string SectionCode, 
                        int CampaignSettingKind, 
                        int GoodsMakerCode, 
                        string GoodsMakerName, 
                        string GoodsNo, 
                        int BLGoodsCode, 
                        string GoodsName, 
                        int BLGroupCode, 
                        string SalesCode, 
                        int SalesPriceSetDiv, 
                        string CustomerCode, 
                        double DiscountRate, 
                        double RateVal, 
                        double PriceFl, 
                        int PriceStartDate, 
                        int PriceEndDate, 
                        System.Guid FilterGuid, 
                        int RowDeleteFlg, 
                        string UpdateTime2) {
                CampaignMngRow rowCampaignMngRow = ((CampaignMngRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        RowNo,
                        UpdateTime,
                        CampaignCode,
                        CampaignName,
                        SectionCode,
                        CampaignSettingKind,
                        GoodsMakerCode,
                        GoodsMakerName,
                        GoodsNo,
                        BLGoodsCode,
                        GoodsName,
                        BLGroupCode,
                        SalesCode,
                        SalesPriceSetDiv,
                        CustomerCode,
                        DiscountRate,
                        RateVal,
                        PriceFl,
                        PriceStartDate,
                        PriceEndDate,
                        FilterGuid,
                        RowDeleteFlg,
                        UpdateTime2};
                rowCampaignMngRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowCampaignMngRow);
                return rowCampaignMngRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                CampaignMngDataTable cln = ((CampaignMngDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CampaignMngDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRowNo = base.Columns["RowNo"];
                this.columnUpdateTime = base.Columns["UpdateTime"];
                this.columnCampaignCode = base.Columns["CampaignCode"];
                this.columnCampaignName = base.Columns["CampaignName"];
                this.columnSectionCode = base.Columns["SectionCode"];
                this.columnCampaignSettingKind = base.Columns["CampaignSettingKind"];
                this.columnGoodsMakerCode = base.Columns["GoodsMakerCode"];
                this.columnGoodsMakerName = base.Columns["GoodsMakerName"];
                this.columnGoodsNo = base.Columns["GoodsNo"];
                this.columnBLGoodsCode = base.Columns["BLGoodsCode"];
                this.columnGoodsName = base.Columns["GoodsName"];
                this.columnBLGroupCode = base.Columns["BLGroupCode"];
                this.columnSalesCode = base.Columns["SalesCode"];
                this.columnSalesPriceSetDiv = base.Columns["SalesPriceSetDiv"];
                this.columnCustomerCode = base.Columns["CustomerCode"];
                this.columnDiscountRate = base.Columns["DiscountRate"];
                this.columnRateVal = base.Columns["RateVal"];
                this.columnPriceFl = base.Columns["PriceFl"];
                this.columnPriceStartDate = base.Columns["PriceStartDate"];
                this.columnPriceEndDate = base.Columns["PriceEndDate"];
                this.columnFilterGuid = base.Columns["FilterGuid"];
                this.columnRowDeleteFlg = base.Columns["RowDeleteFlg"];
                this.columnUpdateTime2 = base.Columns["UpdateTime2"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRowNo = new global::System.Data.DataColumn("RowNo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRowNo);
                this.columnUpdateTime = new global::System.Data.DataColumn("UpdateTime", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpdateTime);
                this.columnCampaignCode = new global::System.Data.DataColumn("CampaignCode", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaignCode);
                this.columnCampaignName = new global::System.Data.DataColumn("CampaignName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaignName);
                this.columnSectionCode = new global::System.Data.DataColumn("SectionCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSectionCode);
                this.columnCampaignSettingKind = new global::System.Data.DataColumn("CampaignSettingKind", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCampaignSettingKind);
                this.columnGoodsMakerCode = new global::System.Data.DataColumn("GoodsMakerCode", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoodsMakerCode);
                this.columnGoodsMakerName = new global::System.Data.DataColumn("GoodsMakerName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoodsMakerName);
                this.columnGoodsNo = new global::System.Data.DataColumn("GoodsNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoodsNo);
                this.columnBLGoodsCode = new global::System.Data.DataColumn("BLGoodsCode", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBLGoodsCode);
                this.columnGoodsName = new global::System.Data.DataColumn("GoodsName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoodsName);
                this.columnBLGroupCode = new global::System.Data.DataColumn("BLGroupCode", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBLGroupCode);
                this.columnSalesCode = new global::System.Data.DataColumn("SalesCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSalesCode);
                this.columnSalesPriceSetDiv = new global::System.Data.DataColumn("SalesPriceSetDiv", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSalesPriceSetDiv);
                this.columnCustomerCode = new global::System.Data.DataColumn("CustomerCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCustomerCode);
                this.columnDiscountRate = new global::System.Data.DataColumn("DiscountRate", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDiscountRate);
                this.columnRateVal = new global::System.Data.DataColumn("RateVal", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRateVal);
                this.columnPriceFl = new global::System.Data.DataColumn("PriceFl", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPriceFl);
                this.columnPriceStartDate = new global::System.Data.DataColumn("PriceStartDate", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPriceStartDate);
                this.columnPriceEndDate = new global::System.Data.DataColumn("PriceEndDate", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPriceEndDate);
                this.columnFilterGuid = new global::System.Data.DataColumn("FilterGuid", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFilterGuid);
                this.columnRowDeleteFlg = new global::System.Data.DataColumn("RowDeleteFlg", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRowDeleteFlg);
                this.columnUpdateTime2 = new global::System.Data.DataColumn("UpdateTime2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpdateTime2);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("CampaignMngKey1", new global::System.Data.DataColumn[] {
                                this.columnRowNo}, false));
                this.columnRowNo.AllowDBNull = false;
                this.columnRowNo.Unique = true;
                this.columnRowNo.Caption = "No.";
                this.columnRowNo.DefaultValue = ((int)(0));
                this.columnUpdateTime.AllowDBNull = false;
                this.columnUpdateTime.Caption = "削除日";
                this.columnUpdateTime.DefaultValue = ((string)(""));
                this.columnCampaignCode.AllowDBNull = false;
                this.columnCampaignCode.Caption = "ｺｰﾄﾞ";
                this.columnCampaignCode.DefaultValue = ((int)(0));
                this.columnCampaignName.AllowDBNull = false;
                this.columnCampaignName.Caption = "名称";
                this.columnCampaignName.DefaultValue = ((string)(""));
                this.columnSectionCode.AllowDBNull = false;
                this.columnSectionCode.Caption = "拠点";
                this.columnSectionCode.DefaultValue = ((string)("00"));
                this.columnCampaignSettingKind.AllowDBNull = false;
                this.columnCampaignSettingKind.Caption = "設定種別";
                this.columnCampaignSettingKind.DefaultValue = ((int)(1));
                this.columnGoodsMakerCode.AllowDBNull = false;
                this.columnGoodsMakerCode.Caption = "ﾒｰｶｰ";
                this.columnGoodsMakerCode.DefaultValue = ((int)(0));
                this.columnGoodsMakerName.AllowDBNull = false;
                this.columnGoodsMakerName.Caption = "ﾒｰｶｰ名";
                this.columnGoodsMakerName.DefaultValue = ((string)(""));
                this.columnGoodsNo.AllowDBNull = false;
                this.columnGoodsNo.Caption = "品番";
                this.columnGoodsNo.DefaultValue = ((string)(""));
                this.columnBLGoodsCode.AllowDBNull = false;
                this.columnBLGoodsCode.Caption = "BLｺｰﾄﾞ";
                this.columnBLGoodsCode.DefaultValue = ((int)(0));
                this.columnGoodsName.AllowDBNull = false;
                this.columnGoodsName.Caption = "品名";
                this.columnGoodsName.DefaultValue = ((string)(""));
                this.columnBLGroupCode.AllowDBNull = false;
                this.columnBLGroupCode.Caption = "ｸﾞﾙｰﾌﾟ";
                this.columnBLGroupCode.DefaultValue = ((int)(0));
                this.columnSalesCode.AllowDBNull = false;
                this.columnSalesCode.Caption = "販売区分";
                this.columnSalesCode.DefaultValue = ((string)(""));
                this.columnSalesPriceSetDiv.AllowDBNull = false;
                this.columnSalesPriceSetDiv.Caption = "売価区分";
                this.columnSalesPriceSetDiv.DefaultValue = ((int)(0));
                this.columnCustomerCode.AllowDBNull = false;
                this.columnCustomerCode.Caption = "得意先";
                this.columnCustomerCode.DefaultValue = ((string)(""));
                this.columnDiscountRate.AllowDBNull = false;
                this.columnDiscountRate.Caption = "値引率";
                this.columnDiscountRate.DefaultValue = ((double)(0));
                this.columnRateVal.AllowDBNull = false;
                this.columnRateVal.Caption = "売価率";
                this.columnRateVal.DefaultValue = ((double)(0));
                this.columnPriceFl.AllowDBNull = false;
                this.columnPriceFl.Caption = "売価額";
                this.columnPriceFl.DefaultValue = ((double)(0));
                this.columnPriceStartDate.AllowDBNull = false;
                this.columnPriceStartDate.Caption = "価格開始日";
                this.columnPriceStartDate.DefaultValue = ((int)(0));
                this.columnPriceEndDate.AllowDBNull = false;
                this.columnPriceEndDate.Caption = "価格終了日";
                this.columnPriceEndDate.DefaultValue = ((int)(0));
                this.columnFilterGuid.AllowDBNull = false;
                this.columnRowDeleteFlg.AllowDBNull = false;
                this.columnRowDeleteFlg.Caption = "行削除フラグ";
                this.columnRowDeleteFlg.DefaultValue = ((int)(0));
                this.columnUpdateTime2.Caption = "更新日";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngRow NewCampaignMngRow() {
                return ((CampaignMngRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CampaignMngRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(CampaignMngRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CampaignMngRowChanged != null)) {
                    this.CampaignMngRowChanged(this, new CampaignMngRowChangeEvent(((CampaignMngRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CampaignMngRowChanging != null)) {
                    this.CampaignMngRowChanging(this, new CampaignMngRowChangeEvent(((CampaignMngRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CampaignMngRowDeleted != null)) {
                    this.CampaignMngRowDeleted(this, new CampaignMngRowChangeEvent(((CampaignMngRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CampaignMngRowDeleting != null)) {
                    this.CampaignMngRowDeleting(this, new CampaignMngRowChangeEvent(((CampaignMngRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCampaignMngRow(CampaignMngRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                CampaignMngDataSet ds = new CampaignMngDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CampaignMngDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class CampaignMngRow : global::System.Data.DataRow {
            
            private CampaignMngDataTable tableCampaignMng;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CampaignMngRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCampaignMng = ((CampaignMngDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int RowNo {
                get {
                    return ((int)(this[this.tableCampaignMng.RowNoColumn]));
                }
                set {
                    this[this.tableCampaignMng.RowNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UpdateTime {
                get {
                    return ((string)(this[this.tableCampaignMng.UpdateTimeColumn]));
                }
                set {
                    this[this.tableCampaignMng.UpdateTimeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int CampaignCode {
                get {
                    return ((int)(this[this.tableCampaignMng.CampaignCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.CampaignCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CampaignName {
                get {
                    return ((string)(this[this.tableCampaignMng.CampaignNameColumn]));
                }
                set {
                    this[this.tableCampaignMng.CampaignNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SectionCode {
                get {
                    return ((string)(this[this.tableCampaignMng.SectionCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.SectionCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int CampaignSettingKind {
                get {
                    return ((int)(this[this.tableCampaignMng.CampaignSettingKindColumn]));
                }
                set {
                    this[this.tableCampaignMng.CampaignSettingKindColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int GoodsMakerCode {
                get {
                    return ((int)(this[this.tableCampaignMng.GoodsMakerCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.GoodsMakerCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GoodsMakerName {
                get {
                    return ((string)(this[this.tableCampaignMng.GoodsMakerNameColumn]));
                }
                set {
                    this[this.tableCampaignMng.GoodsMakerNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GoodsNo {
                get {
                    return ((string)(this[this.tableCampaignMng.GoodsNoColumn]));
                }
                set {
                    this[this.tableCampaignMng.GoodsNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int BLGoodsCode {
                get {
                    return ((int)(this[this.tableCampaignMng.BLGoodsCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.BLGoodsCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GoodsName {
                get {
                    return ((string)(this[this.tableCampaignMng.GoodsNameColumn]));
                }
                set {
                    this[this.tableCampaignMng.GoodsNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int BLGroupCode {
                get {
                    return ((int)(this[this.tableCampaignMng.BLGroupCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.BLGroupCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SalesCode {
                get {
                    return ((string)(this[this.tableCampaignMng.SalesCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.SalesCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int SalesPriceSetDiv {
                get {
                    return ((int)(this[this.tableCampaignMng.SalesPriceSetDivColumn]));
                }
                set {
                    this[this.tableCampaignMng.SalesPriceSetDivColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CustomerCode {
                get {
                    return ((string)(this[this.tableCampaignMng.CustomerCodeColumn]));
                }
                set {
                    this[this.tableCampaignMng.CustomerCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double DiscountRate {
                get {
                    return ((double)(this[this.tableCampaignMng.DiscountRateColumn]));
                }
                set {
                    this[this.tableCampaignMng.DiscountRateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double RateVal {
                get {
                    return ((double)(this[this.tableCampaignMng.RateValColumn]));
                }
                set {
                    this[this.tableCampaignMng.RateValColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double PriceFl {
                get {
                    return ((double)(this[this.tableCampaignMng.PriceFlColumn]));
                }
                set {
                    this[this.tableCampaignMng.PriceFlColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PriceStartDate {
                get {
                    return ((int)(this[this.tableCampaignMng.PriceStartDateColumn]));
                }
                set {
                    this[this.tableCampaignMng.PriceStartDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PriceEndDate {
                get {
                    return ((int)(this[this.tableCampaignMng.PriceEndDateColumn]));
                }
                set {
                    this[this.tableCampaignMng.PriceEndDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid FilterGuid {
                get {
                    return ((global::System.Guid)(this[this.tableCampaignMng.FilterGuidColumn]));
                }
                set {
                    this[this.tableCampaignMng.FilterGuidColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int RowDeleteFlg {
                get {
                    return ((int)(this[this.tableCampaignMng.RowDeleteFlgColumn]));
                }
                set {
                    this[this.tableCampaignMng.RowDeleteFlgColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UpdateTime2 {
                get {
                    try {
                        return ((string)(this[this.tableCampaignMng.UpdateTime2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'CampaignMng\' にある列 \'UpdateTime2\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableCampaignMng.UpdateTime2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUpdateTime2Null() {
                return this.IsNull(this.tableCampaignMng.UpdateTime2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUpdateTime2Null() {
                this[this.tableCampaignMng.UpdateTime2Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class CampaignMngRowChangeEvent : global::System.EventArgs {
            
            private CampaignMngRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngRowChangeEvent(CampaignMngRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CampaignMngRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591