using System.IO;
using System.Text;

namespace Broadleaf.Application.Remoting
{
    /// <summary>
    /// 担当者コード変換対象設定リスト
    /// </summary>
    /// <remarks>
    /// <br>Update Note : 2018/07/25 呉軍</br>
    /// <br>管理番号    : 11400935-00</br>
    /// <br>            : Redmine#49726 担当者コード変換対象テーブルとカラムの追加</br>
    /// </remarks>
    public static class XMLEmployeeConvertList
    {
        #region convertList
        public static string convertList = @"<?xml version=""1.0"" encoding=""utf-8"" standalone=""yes""?>
<ArrayOfEmployeeConvertList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
	<EmployeeConvertList>
		<TargetTable>EMPLOYEERF</TargetTable>
		<TargetTableName>従業員マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>EMPLOYEEDTLRF</TargetTable>
		<TargetTableName>従業員詳細マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>EMPSALESTARGETRF</TargetTable>
		<TargetTableName>従業員別売上目標設定マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>CUSTOMERAGENTCDRF</TargetColumn>
		<TargetColumnName>顧客担当従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>BILLCOLLECTERCDRF</TargetColumn>
		<TargetColumnName>集金担当従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CUSTOMERRF</TargetTable>
		<TargetTableName>得意先マスタ</TargetTableName>
		<TargetColumn>OLDCUSTOMERAGENTCDRF</TargetColumn>
		<TargetColumnName>旧顧客担当従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>OPERATIONSTRF</TargetTable>
		<TargetTableName>オペレーション設定マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>EMPLOYEEROLESTRF</TargetTable>
		<TargetTableName>従業員ロール設定マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>UOESUPPLIERRF</TargetTable>
		<TargetTableName>UOE発注先マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CAMPAIGNLINKRF</TargetTable>
		<TargetTableName>キャンペーン関連マスタ</TargetTableName>
		<TargetColumn>CUSTOMERAGENTCDRF</TargetColumn>
		<TargetColumnName>顧客担当従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CAMPAIGNTARGETRF</TargetTable>
		<TargetTableName>キャンペーン目標設定マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>FELICAMNGRF</TargetTable>
		<TargetTableName>FeliCa管理マスタ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>INPUTAGENCDRF</TargetColumn>
		<TargetColumnName>入力担当者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>SALESINPUTCODERF</TargetColumn>
		<TargetColumnName>売上入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>FRONTEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>受付従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESSLIPRF</TargetTable>
		<TargetTableName>売上データ</TargetTableName>
		<TargetColumn>SALESEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>販売従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>INPUTAGENCDRF</TargetColumn>
		<TargetColumnName>入力担当者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>SALESINPUTCODERF</TargetColumn>
		<TargetColumnName>売上入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>FRONTEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>受付従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SALESHISTORYRF</TargetTable>
		<TargetTableName>売上履歴データ</TargetTableName>
		<TargetColumn>SALESEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>販売従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>DEPOSITAGENTCODERF</TargetColumn>
		<TargetColumnName>入金担当者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>DEPSITMAINRF</TargetTable>
		<TargetTableName>入金マスタ</TargetTableName>
		<TargetColumn>DEPOSITINPUTAGENTCDRF</TargetColumn>
		<TargetColumnName>入金入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>DEPOSITALWRF</TargetTable>
		<TargetTableName>入金引当マスタ</TargetTableName>
		<TargetColumn>DEPOSITAGENTCODERF</TargetColumn>
		<TargetColumnName>入金担当者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>STOCKSLIPRF</TargetTable>
		<TargetTableName>仕入データ</TargetTableName>
		<TargetColumn>STOCKINPUTCODERF</TargetColumn>
		<TargetColumnName>仕入入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>STOCKSLIPRF</TargetTable>
		<TargetTableName>仕入データ</TargetTableName>
		<TargetColumn>STOCKAGENTCODERF</TargetColumn>
		<TargetColumnName>仕入担当者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>STOCKDETAILRF</TargetTable>
		<TargetTableName>仕入明細データ</TargetTableName>
		<TargetColumn>STOCKINPUTCODERF</TargetColumn>
		<TargetColumnName>仕入入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>CIRCULINVENTHISDATARF</TargetTable>
		<TargetTableName>循環棚卸履歴データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>GOODSMTTLSASLIPRF</TargetTable>
		<TargetTableName>商品別売上月次集計データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>INSPECTDATARF</TargetTable>
		<TargetTableName>検品データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>MTTLSALESSLIPRF</TargetTable>
		<TargetTableName>売上月次集計データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>MTTLSTOCKSLIPRF</TargetTable>
		<TargetTableName>仕入月次集計データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>PCCTTLSTRF</TargetTable>
		<TargetTableName>PCC全体設定マスタ</TargetTableName>
		<TargetColumn>FRONTEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>受付従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SCMTTLSTRF</TargetTable>
		<TargetTableName>SCM全体設定マスタ</TargetTableName>
		<TargetColumn>FRONTEMPLOYEECDRF</TargetColumn>
		<TargetColumnName>受付従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>SCMTTLSTRF</TargetTable>
		<TargetTableName>SCM全体設定マスタ</TargetTableName>
		<TargetColumn>SALESINPUTCODERF</TargetColumn>
		<TargetColumnName>売上入力者コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>STOCKMOVERF</TargetTable>
		<TargetTableName>在庫移動データ</TargetTableName>
		<TargetColumn>STOCKMVEMPCODERF</TargetColumn>
		<TargetColumnName>在庫移動入力従業員コード</TargetColumnName>
	</EmployeeConvertList>
	<EmployeeConvertList>
		<TargetTable>UOEORDERDTLRF</TargetTable>
		<TargetTableName>UOE発注データ</TargetTableName>
		<TargetColumn>EMPLOYEECODERF</TargetColumn>
		<TargetColumnName>従業員コード</TargetColumnName>
	</EmployeeConvertList>
</ArrayOfEmployeeConvertList>";
        #endregion
        public static MemoryStream ms()
        {
            return new MemoryStream(Encoding.UTF8.GetBytes(convertList));
        }
    }
}