using System.IO;
using System.Text;

namespace Broadleaf.Application.Remoting
{
    /// <summary>
    /// 倉庫コード変換対象設定リスト
    /// </summary>
    /// <remarks>
    /// <br>Update Note : 2018/07/25 呉軍</br>
    /// <br>管理番号    : 11400935-00</br>
    /// <br>            : Redmine#49726 倉庫コード変換対象テーブルとカラムの追加</br>
    /// </remarks>
    public static class XMLWarehouseConvertList
    {
        #region convertList
        public static string convertList = @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<ArrayOfWarehouseConvertList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
<WarehouseConvertList>
	<TargetTable>SECINFOSETRF</TargetTable>
	<TargetTableName>拠点情報設定マスタ</TargetTableName>
	<TargetColumn>SECTWAREHOUSECD1RF</TargetColumn>
	<TargetColumnName>拠点倉庫コード１</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>SECINFOSETRF</TargetTable>
	<TargetTableName>拠点情報設定マスタ</TargetTableName>
	<TargetColumn>SECTWAREHOUSECD2RF</TargetColumn>
	<TargetColumnName>拠点倉庫コード２</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>SECINFOSETRF</TargetTable>
	<TargetTableName>拠点情報設定マスタ</TargetTableName>
	<TargetColumn>SECTWAREHOUSECD3RF</TargetColumn>
	<TargetColumnName>拠点倉庫コード３</TargetColumnName>
	</WarehouseConvertList>
/***
<WarehouseConvertList>
	<TargetTable>WAREHOUSERF</TargetTable>
	<TargetTableName>倉庫マスタ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>WAREHOUSERF</TargetTable>
	<TargetTableName>倉庫マスタ</TargetTableName>
	<TargetColumn>MAINMNGWAREHOUSECDRF</TargetColumn>
	<TargetColumnName>主管倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>CUSTOMERRF</TargetTable>
	<TargetTableName>得意先マスタ</TargetTableName>
	<TargetColumn>CUSTWAREHOUSECDRF</TargetColumn>
	<TargetColumnName>得意先優先倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKRF</TargetTable>
	<TargetTableName>在庫マスタ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>ORDERPOINTSTRF</TargetTable>
	<TargetTableName>発注点設定マスタ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>SLIPOUTPUTSETRF</TargetTable>
	<TargetTableName>伝票出力先設定マスタ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>SALESDETAILRF</TargetTable>
	<TargetTableName>売上明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>SALESHISTDTLRF</TargetTable>
	<TargetTableName>売上履歴明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKDETAILRF</TargetTable>
	<TargetTableName>仕入明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKSLHISTDTLRF</TargetTable>
	<TargetTableName>仕入履歴明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKMOVERF</TargetTable>
	<TargetTableName>在庫移動データ</TargetTableName>
	<TargetColumn>BFENTERWAREHCODERF</TargetColumn>
	<TargetColumnName>移動元倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKMOVERF</TargetTable>
	<TargetTableName>在庫移動データ</TargetTableName>
	<TargetColumn>AFENTERWAREHCODERF</TargetColumn>
	<TargetColumnName>移動先倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKADJUSTDTLRF</TargetTable>
	<TargetTableName>在庫調整明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKACPAYHISTRF</TargetTable>
	<TargetTableName>在庫受払履歴データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKACPAYHISTRF</TargetTable>
	<TargetTableName>在庫受払履歴データ</TargetTableName>
	<TargetColumn>BFENTERWAREHCODERF</TargetColumn>
	<TargetColumnName>移動元倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKACPAYHISTRF</TargetTable>
	<TargetTableName>在庫受払履歴データ</TargetTableName>
	<TargetColumn>AFENTERWAREHCODERF</TargetColumn>
	<TargetColumnName>移動先倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>STOCKHISTORYRF</TargetTable>
	<TargetTableName>在庫履歴データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>UOEORDERDTLRF</TargetTable>
	<TargetTableName>UOE発注データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>CIRCULINVENTHISDATARF</TargetTable>
	<TargetTableName>循環棚卸履歴データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>CIRCULINVENTHISDTLRF</TargetTable>
	<TargetTableName>循環棚卸履歴明細データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INSPECTDATARF</TargetTable>
	<TargetTableName>検品データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTORYDATARF</TargetTable>
	<TargetTableName>棚卸データ</TargetTableName>
	<TargetColumn>WAREHOUSECODERF</TargetColumn>
	<TargetColumnName>倉庫コード</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE1RF</TargetColumn>
	<TargetColumnName>選択倉庫コード１</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE2RF</TargetColumn>
	<TargetColumnName>選択倉庫コード２</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE3RF</TargetColumn>
	<TargetColumnName>選択倉庫コード３</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE4RF</TargetColumn>
	<TargetColumnName>選択倉庫コード４</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE5RF</TargetColumn>
	<TargetColumnName>選択倉庫コード５</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE6RF</TargetColumn>
	<TargetColumnName>選択倉庫コード６</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE7RF</TargetColumn>
	<TargetColumnName>選択倉庫コード７</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE8RF</TargetColumn>
	<TargetColumnName>選択倉庫コード８</TargetColumnName>
	</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE9RF</TargetColumn>
	<TargetColumnName>選択倉庫コード９</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>SELWAREHOUSECODE10RF</TargetColumn>
	<TargetColumnName>選択倉庫コード１０</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>WAREHOUSECODESTRF</TargetColumn>
	<TargetColumnName>倉庫コード開始</TargetColumnName>
</WarehouseConvertList>
<WarehouseConvertList>
	<TargetTable>INVENTDATAPRERF</TargetTable>
	<TargetTableName>棚卸データ（準備処理履歴）</TargetTableName>
	<TargetColumn>WAREHOUSECODEEDRF</TargetColumn>
	<TargetColumnName>倉庫コード終了</TargetColumnName>
</WarehouseConvertList>
****/
</ArrayOfWarehouseConvertList>";
        #endregion
        public static MemoryStream ms()
        {
            return new MemoryStream(Encoding.UTF8.GetBytes(convertList));
        }
    }
}