# BugSearch2 統合テストデフォルト設定
# このファイルは各ジョブタイプのデフォルトチェックボックス設定を管理します
# Version: v4.11.5

version: "1.0.0"

# Context7統合分析のデフォルト設定
context7:
  # デフォルトで選択される技術スタック（複数可）- 全22種類
  default_tech_stacks:
    # フロントエンド
    - react
    - angular
    - vue
    - svelte
    # バックエンド
    - express
    - nestjs
    - fastapi
    - django
    - flask
    - spring-boot
    # データベース
    - elasticsearch
    - cassandra
    - mongodb
    - redis
    - mysql
    - postgresql
    - sqlserver
    - oracle
    - memcached
    # その他
    - typescript
    - nodejs
    - go

  # デフォルトで選択されるトピック（複数可）- 全18種類
  default_topics:
    - security
    - performance
    - database
    - solid
    - best-practices
    - error-handling
    - testing
    - accessibility
    - optimization
    - architecture
    - patterns
    - styling
    - state-management
    - routing
    - deployment
    - monitoring
    - api-integration
    - data-validation

# 統合テストのデフォルト設定
integration_test:
  # デフォルトで選択されるプロジェクトタイプ（複数可）- 全22種類
  default_project_types:
    # フロントエンド
    - react
    - angular
    - vue
    - svelte
    # バックエンド
    - express
    - nestjs
    - fastapi
    - django
    - flask
    - spring-boot
    # データベース
    - elasticsearch
    - cassandra
    - mongodb
    - redis
    - mysql
    - postgresql
    - sqlserver
    - oracle
    - memcached
    # その他
    - typescript
    - nodejs
    - go

  # デフォルトで選択されるトピック（複数可）- 全18種類
  default_topics:
    - security
    - performance
    - database
    - solid
    - best-practices
    - error-handling
    - testing
    - accessibility
    - optimization
    - architecture
    - patterns
    - styling
    - state-management
    - routing
    - deployment
    - monitoring
    - api-integration
    - data-validation

  # インデックス作成オプション
  default_max_file_mb: 4
  default_worker_count: 4

# インデックス作成のデフォルト設定
index:
  default_max_file_mb: 4
  default_worker_count: 4
  default_exclude_langs: []  # 除外する言語リスト（空=除外なし）

# AI分析のデフォルト設定
advise:
  default_complete_report: false
  default_max_complete_items: 100

# データベース統合テストのデフォルト設定
database_integration_test:
  # デフォルトで選択されるデータベースタイプ（複数可）- データベース関連9種類
  default_database_types:
    - elasticsearch
    - cassandra
    - mongodb
    - redis
    - mysql
    - postgresql
    - sqlserver
    - oracle
    - memcached

  # デフォルトで選択されるトピック（複数可）- 全18種類
  default_topics:
    - security
    - performance
    - database
    - solid
    - best-practices
    - error-handling
    - testing
    - accessibility
    - optimization
    - architecture
    - patterns
    - styling
    - state-management
    - routing
    - deployment
    - monitoring
    - api-integration
    - data-validation
