namespace Broadleaf.Library.Runtime.InteropServices
{
    /// <summary>
    /// Felica.dllに対するエラーコード列挙体です。
    /// </summary>
    public enum FeliCaErrorType : uint
    {
        FELICA_ERROR_NOT_OCCURRED = 1000,
        FELICA_UNKNOWN_ERROR = 1001,
        FELICA_ILLEGAL_ARGUMENT = 1002,
        FELICA_MEMORY_ALLOCATION_ERROR = 1003,
        FELICA_THREAD_CREATION_ERROR = 1004,
        FELICA_LIBRARY_NOT_INITIALIZED = 1005,
        FELICA_LIBRARY_ALREADY_INITIALIZED = 1006,
        FELICA_INVALID_FILE_NAME = 1007,
        FELICA_FILE_NOT_FOUND = 1008,
        FELICA_FILE_OPEN_ERROR = 1009,
        FELICA_FILE_NOT_OPENED = 1010,
        FELICA_FILE_ALREADY_OPENED = 1011,
        FELICA_INVALID_DIRECTORY_NAME = 1012,
        FELICA_DIRECTORY_NOT_FOUND = 1013,
        FELICA_DIRECTORY_OPEN_ERROR = 1014,
        FELICA_DIRECTORY_NOT_OPENED = 1015,
        FELICA_DIRECTORY_ALREADY_OPENED = 1016,
        FELICA_INVALID_COMMUNICATIONS_PORT_NAME = 1017,
        FELICA_COMMUNICATIONS_PORT_NOT_FOUND = 1018,
        FELICA_COMMUNICATIONS_PORT_OPEN_ERROR = 1019,
        FELICA_COMMUNICATIONS_PORT_NOT_OPENED = 1020,
        FELICA_COMMUNICATIONS_PORT_ALREADY_OPENED = 1021,
        FELICA_INVALID_TIME_OUT = 1022,
        FELICA_INVALID_BAUD_RATE = 1023,
        FELICA_INVALID_RETRY_COUNT = 1024,
        FELICA_READER_WRITER_CONTROL_LIBRARY_NOT_FOUND = 1025,
        FELICA_READER_WRITER_CONTROL_LIBRARY_LOAD_ERROR = 1026,
        FELICA_READER_WRITER_OPEN_ERROR = 1027,
        FELICA_READER_WRITER_OPEN_AUTO_ERROR = 1028,
        FELICA_READER_WRITER_NOT_OPENED = 1029,
        FELICA_READER_WRITER_ALREADY_OPENED = 1030,
        FELICA_READER_WRITER_RECONNECT_ERROR = 1031,
        FELICA_MESSAGE_OF_CARD_FIND_REGISTRATION_ERROR = 1032,
        FELICA_MESSAGE_OF_CARD_LOSS_REGISTRATION_ERROR = 1033,
        FELICA_CALL_BACK_PARAMETERS_NOT_SETTED = 1034,
        FELICA_SUCCESSIVE_POLLING_FOR_CALL_BACK_NOT_STARTED = 1035,
        FELICA_POLLING_ERROR = 1036,
        FELICA_REQUEST_RESPONSE_ERROR = 1037,
        FELICA_REQUEST_SERVICE_ERROR = 1038,
        FELICA_MUTUAL_AUTHENTICATION_ERROR = 1039,
        FELICA_READ_BLOCK_ERROR = 1040,
        FELICA_WRITE_BLOCK_ERROR = 1041,
        FELICA_READ_BLOCK_WITHOUT_ENCRYPTION_ERROR = 1042,
        FELICA_WRITE_BLOCK_WIHTOUT_ENCRYPTION_ERROR = 1043,
        FELICA_DUMB_ERROR = 1044,
        FELICA_MAKE_ACCESS_KEYS_ERROR = 1045,
        FELICA_CARD_INFORMATION_NOT_FOUND = 1046,
        FELICA_CARD_INFORMATION_ACCESS_ERROR = 1047,
        FELICA_INVALID_CARD_INDEX = 1048,
        FELICA_CARD_IDM_UNMATCHED = 1049,
        FELICA_MUTUAL_AUTHENTICATION_NOT_DONE = 1050,
        FELICA_ILLEGAL_SERVICE_SETTED = 1051,
        FELICA_BLOCK_LIST_GENERATION_ERROR = 1052,
        FELICA_ACCESS_LIBRARY_FUNCTION_ERROR = 1053,
        FELICA_EXCHANGE_KEY_ERROR = 1054,
        FELICA_SUCCESSIVE_POLLING_FOR_CALL_BACK_ALREADY_STARTED = 1055,
        FELICA_MESSAGE_OF_READER_WRITER_CONNECT_REGISTRATION_ERROR = 1056,
        FELICA_MESSAGE_OF_READER_WRITER_PULLOUT_REGISTRATION_ERROR = 1057,
        FELICA_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_NOT_STARTED = 1058,
        FELICA_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_ALREADY_STARTED = 1059,
        FELICA_API_NOT_IMPLEMENTED_FOR_THIS_PLATHOME = 1060,
        FELICA_REQUEST_SYSTEM_CODE_ERROR = 1061,
        FELICA_SEARCH_SERVICE_CODE_ERROR = 1062,
        FELICA_APPEND_KEY_LIST_TO_ACCESS_KEYS_ERROR = 1063,
        FELICA_SET_SHARED_OPEN_MODE_ERROR = 1064,
        FELICA_TRANSACTION_LOCK_ERROR = 1065,
        FELICA_TRANSACTION_UNLOCK_ERROR = 1066,
        FELICA_SET_LOCK_TIMEOUT_ERROR = 1067,
        FELICA_GET_LOCK_TIMEOUT_ERROR = 1068,
        FELICA_GET_DEVICE_INFO_FAILED = 1069,
        FELICA_GET_OPEN_PROCCESS_COUNT_FAILED = 1070,
        FELICA_SET_POLLING_TIMEOUT_ERROR = 1071,
        FELICA_GET_POLLING_TIMEOUT_ERROR = 1072,
        FELICA_CHANGE_PARAMETER_ERROR = 1073,
        FELICA_GET_LAST_ERROR_ERROR = 1074,
        FELICA_GET_ATTRIBUTE_ERROR = 1075,
        FELICA_COMMUNICATE_THRU_ERROR = 1076,
        FELICA_RF_SWITCH_ERROR = 1077,
        FELICA_REQUEST_BLOCK_INFO_EX_ERROR = 1078,
        FELICA_GET_CONTAINER_ISSUE_INFO_ERROR = 1079,
        FELICA_SET_REL_SERVICE_PACKAGE_ERROR = 1080,
        FELICA_FALP_OPENED = 1081,
        FELICA_FALP_NOT_OPENED = 1082,
        FELICA_FALP_LIBRARY_ERROR = 1083,
        FELICA_FALP_LIBRARY_INITIALIZE_ERROR = 1084,
        FELICA_FALP_LIBRARY_LOAD_ERROR = 1085,
        FELICA_GET_SEQUENSE_NUMBER_ERROR = 1086,
        FELICA_ILLEGAL_ARGUMENT_ON_CURRENT_CODE_LENGTH_MODE = 1087,
    }

    /// <summary>
    /// RW.dllに対するエラーコード列挙体です。
    /// </summary>
    public enum RwErrorType : uint
    {
        RW_ERROR_NOT_OCCURRED = 100,
        RW_UNKNOWN_ERROR = 101,
        RW_ILLEGAL_ARGUMENT = 102,
        RW_MEMORY_ALLOCATION_ERROR = 103,
        RW_THREAD_CREATION_ERROR = 104,
        RW_LIBRARY_NOT_INITIALIZED = 105,
        RW_LIBRARY_ALREADY_INITIALIZED = 106,
        RW_INVALID_FILE_NAME = 107,
        RW_FILE_NOT_FOUND = 108,
        RW_FILE_OPEN_ERROR = 109,
        RW_FILE_NOT_OPENED = 110,
        RW_FILE_ALREADY_OPENED = 111,
        RW_INVALID_DIRECTORY_NAME = 112,
        RW_DIRECTORY_NOT_FOUND = 113,
        RW_DIRECTORY_OPEN_ERROR = 114,
        RW_DIRECTORY_NOT_OPENED = 115,
        RW_DIRECTORY_ALREADY_OPENED = 116,
        RW_INVALID_COMMUNICATIONS_PORT_NAME = 117,
        RW_COMMUNICATIONS_PORT_NOT_FOUND = 118,
        RW_COMMUNICATIONS_PORT_OPEN_ERROR = 119,
        RW_COMMUNICATIONS_PORT_NOT_OPENED = 120,
        RW_COMMUNICATIONS_PORT_ALREADY_OPENED = 121,
        RW_INVALID_TIME_OUT = 122,
        RW_INVALID_BAUD_RATE = 123,
        RW_PLUGINS_HOME_DIRECTORY_NOT_SETTED = 124,
        RW_PLUGINS_HOME_DIRECTORY_NOT_FOUND = 125,
        RW_PLUGINS_INITIALIZE_ERROR = 126,
        RW_PLUGIN_NOT_FOUND = 127,
        RW_COMMAND_PLUGIN_NOT_FOUND = 128,
        RW_DEVICE_PLUGIN_NOT_FOUND = 129,
        RW_SECURITY_PLUGIN_NOT_FOUND = 130,
        RW_TABLE_ACCESS_ERROR = 131,
        RW_COMMAND_NOT_FOUND = 132,
        RW_SCRIPT_EXECUTION_ERROR = 133,
        RW_COMMUNICATIONS_PORT_INITIALIZE_ERROR = 134,
        RW_COMMUNICATIONAS_PORT_SET_TIME_OUT_ERROR = 135,
        RW_COMMUNICATIONS_PORT_SET_TIME_OUT_ERROR = 135,
        RW_ILLEGAL_COMMUNICATIONS_PORT_STATUS = 136,
        RW_COMMUNICATIONS_PORT_MASKING_ERROR = 137,
        RW_COMMUNICATIONAS_PORT_PURGING_ERROR = 138,
        RW_COMMUNICATIONS_PORT_PURGING_ERROR = 138,
        RW_PLAIN_DATA_LOAD_ERROR = 139,
        RW_PLAIN_DATA_SAVE_ERROR = 140,
        RW_CIPHER_DATA_LOAD_ERROR = 141,
        RW_CIPHER_DATA_SAVE_ERROR = 142,
        RW_RANDOM_NUMBER_NOT_SETTED = 143,
        RW_TRANSACTION_ID_NOT_SETTED = 144,
        RW_TRANSACTION_KEY_ACCESS_ERROR = 145,
        RW_ILLEGAL_TRANSACTION_KEY = 146,
        RW_COMMUNICATIONS_PARITY_ERROR = 147,
        RW_NAK_RECEIVED = 148,
        RW_SYNTAX_ERROR = 149,
        RW_ILLEGAL_PACKET_RECEIVED = 150,
        RW_SESSION_COUNT_OVER = 151,
        RW_RESPONSE_PACKET_NOT_RECEIVED = 152,
        RW_DATA_SENDING_ERROR = 153,
        RW_DATA_SENDING_TIME_OUT = 154,
        RW_DATA_RECEIVING_ERROR = 155,
        RW_DATA_RECEIVING_TIME_OUT = 156,
        RW_CARD_NOT_FOUND = 157,
        RW_INVALID_CARD_INDEX = 158,
        RW_CARD_STATUS_FLAG_ERROR = 159,
        RW_DUMB_RESPONSE_PACKET_NOT_RECEIVED = 160,
        RW_USER_KEY_ERROR = 161,
        RW_USER_KEY_EXPIRATION = 162,
        RW_CALL_BACK_PARAMETERS_NOT_SETTED = 163,
        RW_MESSAGE_OF_READER_WRITER_CONNECT_REGISTRATION_ERROR = 164,
        RW_MESSAGE_OF_READER_WRITER_PULLOUT_REGISTRATION_ERROR = 165,
        RW_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_NOT_STARTED = 166,
        RW_PLUG_AND_PLAY_WATCH_FOR_CALL_BACK_ALREADY_STARTED = 167,
        RW_WINDOW_CLASS_OF_PLUG_AND_PLAY_REGISTRATION_ERROR = 168,
        RW_WINDOW_OF_PLUG_AND_PLAY_CREATE_ERROR = 169,
        RW_GUID_DEVICE_INFORMATION_SET_ERROR = 170,
        RW_GUID_INTERFACE_DATA_ERROR = 171,
        RW_GUID_SYMBOLIC_DATA_ERROR = 172,
        RW_API_NOT_IMPLEMENTED_FOR_THIS_PLATHOME = 173,
        RW_REQUEST_SYSTEM_CODE_ERROR = 174,
        RW_SEARCH_SERVICE_CODE_ERROR = 175,
        RW_USB_COMMUNICATION_ERROR = 176,
        RW_READER_WRITER_DISCONNECTED = 177,
        RW_NO_SYSTEM_RESOURCES_ERROR = 178,
        RW_COMMAND_CHECKSUM_ERROR = 179,
        RW_COMMAND_IDTR_ERROR = 180,
        RW_READER_WRITER_MODE_ERROR = 181,
        RW_INVALID_COMMAND_PACKET_PARAMETER = 182,
        RW_INVALID_COMMAND_CODE = 183,
        RW_READER_WRITER_VERSION_MISMATCH = 184,
        RW_ILLEGAL_COMMAND_PACKET = 185,
        RW_READER_WRITER_UNIT_NUMBER_ERROR = 186,
        RW_LOCK_TIMEOUT = 187,
        RW_GET_ACCESS_AUTHORITY_ERROR = 188,
        RW_READER_WRITER_VERSION_UNSUPPORTED = 189
    }

    /// <summary>
    /// Felica.dllに対するエラーメッセージ列挙体です。
    /// </summary>
    public enum FeliCaErrorTypeMsg
    {
        エラーはありません = 1000,
        未定義のエラーです = 1001,
        関数の引数が不正です = 1002,
        メモリの確保ができません = 1003,
        スレッドの生成に失敗しました = 1004,
        ライブラリが初期化されていません = 1005,
        ライブラリはすでに初期化されています = 1006,
        不正なファイル名が指定されました = 1007,
        ファイルを見つけることができません = 1008,
        ファイルをオープンすることができません = 1009,
        ファイルがオープンされていません = 1010,
        ファイルはすでにオープンされています = 1011,
        不正なディレクトリ名が指定されました = 1012,
        ディレクトリを見つけることができません = 1013,
        ディレクトリをオープンすることができません = 1014,
        ディレクトリがオープンされていません = 1015,
        ディレクトリはすでにオープンされています = 1016,
        不正なポート名が指定されました = 1017,
        ポートを見つけることができせん = 1018,
        ポートをオープンすることがきません = 1019,
        ポートがオープンされていません = 1020,
        ポートはすでにオープンされています = 1021,
        タイムアウトの値が不正です = 1022,
        ボーレートの値が不正です = 1023,
        リトライカウントの値が不正です = 1024,
        FeliCaリーダーライタコントロールライブラリを見つけることができません = 1025,
        FeliCaリーダーライタコントロールライブラリのロードに失敗しました = 1026,
        リーダーライタのオープンに失敗しました = 1027,
        リーダーライタを自動認識できません = 1028,
        リーダーライタがオープンされていません = 1029,
        リーダーライタはすでにオープンされています = 1030,
        リーダーライタとの再接続に失敗しました = 1031,
        カードがかざされたときに送信するメッセージの登録に失敗しました = 1032,
        カードを見失なったときに送信するメッセージの登録に失敗しました = 1033,
        コールバックパラメータが設定されていません = 1034,
        コールバックを行うための連続ポーリングが開始されていません = 1035,
        ポーリングに失敗しました = 1036,
        カードのモードの取得に失敗しました = 1037,
        カードのエリア・サービス鍵バージョンの取得に失敗しました = 1038,
        カードとの相互認証に失敗しました = 1039,
        カードからのデータの読み込みに失敗しました = 1040,
        カードへのデータの書き込みに失敗しました = 1041,
        カードからの鍵のないサービスからデータの読み込みに失敗しました = 1042,
        カードへの鍵のないサービスへのデータの書き込みに失敗しました = 1043,
        コミュニケートスルーコマンドの発行に失敗しました = 1044,
        アクセス鍵の生成に失敗しました = 1045,
        まだ一度もポーリングが行われていません = 1046,
        カードの情報の取得に失敗しました = 1047,
        カードのインデックスが不正なためカードの情報を取得できませんでした = 1048,
        ポーリングのときに取得したカードIDmと関数引数のカードIDmが一致しなかったため処理を中断しました = 1049,
        相互認証が行われていません = 1050,
        鍵のないサービスへの読み書きに相互認証が必要なサービスが指定されました = 1051,
        ブロックリストを自動生成することができないサービスCashBackandDecrementが指定されました = 1052,
        FeliCaアクセスライブラリのAPIの呼び出しに失敗しました = 1053,
        鍵の変更に失敗しました = 1054,
        連続ポーリングはすでに起動しています = 1055,
        リーダーライタが接続されたときに送信するメッセージ登録に失敗しました = 1056,
        リーダーライタが抜かれたときに送信するメッセージ登録に失敗しました = 1057,
        プラグアンドプレイ監視は起動していません = 1058,
        プラグアンドプレイ監視はすでに起動しています = 1059,
        このOSでは実装されていいなAPIです = 1060,
        カードのシステムコードリストの取得に失敗しました = 1061,
        カードのサービスコードリストの取得に失敗しました = 1062,
        アクセス鍵への鍵の追加に失敗しました = 1063,
        オープンモードの設定に失敗しました = 1064,
        アクセス権獲得ロックに失敗しました = 1065,
        アクセス権解放アンロックに失敗しました = 1066,
        アクセス権獲得タイムアウト設定に失敗しました = 1067,
        アクセス権獲得タイムアウト取得に失敗しました = 1068,
        デバイス情報取得に失敗しました = 1069,
        共有プロセス数の取得に失敗しました = 1070,
        ポーリングタイムアウト設定に失敗しました = 1071,
        ポーリングタイムアウト取得に失敗しました = 1072,
        リーダーライタの設定変更に失敗しました = 1073,
        リーダーライタから最新のエラーコードが取得できませんでした = 1074,
        リーダーライタから属性情報が取得できませんでした = 1075,
        CommunicateThruコマンドの実行に失敗しました = 1076,
        RFSwitchのON・OFFの設定に失敗しました = 1077,
        空きブロック数の取得に失敗しました = 1078,
        コンテナ発行情報の取得に失敗しました = 1079,
        認証連携の設定に失敗しました = 1080,
        FALPモードのため処理できません = 1081,
        FALPモードではありません = 1082,
        FALPライブラリでエラーが発生しました = 1083,
        FALPライブラリの初期化に失敗しました = 1084,
        FALPライブラリのロードに失敗しました = 1085,
        シーケンス番号の取得に失敗しました = 1086,
        現在のノードコード長では処理できません = 1087,
    }

 /// <summary>
    /// RW.dllに対するエラーメッセージ列挙体です。
    /// </summary>
    public enum RwErrorTypeMsg
    {
        エラーは発生していません = 100,
        未定義のエラーです = 101,
        関数の引数が不正です = 102,
        メモリの確保ができません = 103,
        スレッドの生成に失敗しました = 104,
        ライブラリが初期化されていません = 105,
        ライブラリはすでに初期化されています = 106,
        不正なファイル名が指定されました = 107,
        ファイルを見つけることができません = 108,
        ファイルをオープンすることができません = 109,
        ファイルがオープンされていません = 110,
        ファイルはすでにオープンされています = 111,
        不正なディレクトリ名が指定されました = 112,
        ディレクトリを見つけることができません = 113,
        ディレクトリをオープンすることができません = 114,
        ディレクトリがオープンされていません = 115,
        ディレクトリはすでにオープンされています = 116,
        不正なポート名が指定されました = 117,
        ポートを見つけることができません = 118,
        ポートをオープンすることができません = 119,
        ポートがオープンされていません = 120,
        ポートはすでにオープンされています = 121,
        タイムアウトの値が不正です = 122,
        ボーレートの値が不正です = 123,
        プラグインのホームディレクトリが設定されていません = 124,
        プラグインのホームディレクトリを見つけることができません = 125,
        プラグインの初期化に失敗しました = 126,
        プラグインを見つけることができません = 127,
        コマンド・プラグインを見つけることができません = 128,
        デバイス・プラグインを見つけることができません = 129,
        ユーティリティ・プラグインを見つけることができません = 130,
        テーブルへのアクセスに失敗しました = 131,
        コマンドが見つかりません = 132,
        スクリプトの実行に失敗しました = 133,
        ポートの初期化に失敗しました = 134,
        ポートのタイムアウトの設定に失敗しました = 135,
        ポートのデバイスコントロールの設定が不正です = 136,
        ポートのマスキングに失敗しました = 137,
        ポートのパージングに失敗しました = 138,
        平文データの取得に失敗しました = 139,
        平文データの保存に失敗しました = 140,
        暗号文の取得に失敗しました = 141,
        暗号文の保存に失敗しました = 142,
        認証に必要な乱数列がセットされていません = 143,
        トランザクションIDがセットされていません = 144,
        データを暗号化するために必要なトランザクション鍵の取得に失敗しました = 145,
        データを暗号化するために必要なトランザクション鍵が不正です = 146,
        コミュニケーション・パリティーのチェックで不整合が生じました = 147,
        リーダーライタからNACKを受信しました = 148,
        リーダーライタからシンタックスエラーと通知されました = 149,
        リーダーライタから不正なパケットを受信しました = 150,
        一回のセッションで通信できるシーケンスの回数を超えました = 151,
        リーダーライタからの応答がありません = 152,
        リーダーライタへのデータの送信に失敗しました = 153,
        リーダーライタへのデータの送信でタイムアウトしました = 154,
        リーダーライタからのデータの受信に失敗しました = 155,
        リーダーライタからのデータの受信でタイムアウトしました = 156,
        カードを補足することができませんでした = 157,
        カードのインデックスが不正なためカードの情報を取得できませんでした = 158,
        カードからエラーのステータスフラグを受信しました = 159,
        コミュニケートスルーコマンドに対しての応答がありません = 160,
        ユーザ鍵の指定方法が正しくありません = 161,
        使用期限が切れています = 162,
        コールバックパラメータが設定されていません = 163,
        リーダーライタが接続された時に送信するメッセージ登録に失敗しました = 164,
        リーダーライタが抜かれた時に送信するメッセージ登録に失敗しました = 165,
        プラグアンドプレイ監視は起動していません = 166,
        プラグアンドプレイ監視はすでに起動しています = 167,
        プラグアンドプレイ監視ウィンドウクラスの登録に失敗しました = 168,
        プラグアンドプレイ監視ウィンドウの作成に失敗しました = 169,
        GUIDデバイス情報セットへのハンドルが取得できません = 170,
        GUIDインタフェースデータが取得できません = 171,
        GUIDシンボリック名が取得できません = 172,
        このOSでは実装されていないAPIです = 173,
        カードのシステムコードリストの取得に失敗しました = 174,
        カードのサービスコードリストの取得に失敗しました = 175,
        通信でエラーが発生しました = 176,
        リーダーライタが切断されました = 177,
        ドライバでシステムリソースの確保に失敗しました = 178,
        コマンドパケットのチェックサムエラーが発生しました = 179,
        不正なトランザクションIDが検出されました = 180,
        指定されたコマンドはリーダーライタのモードにより実行されませんでした = 181,
        コマンドパケットにパラメータエラーが存在しました = 182,
        コマンドコードが不正です = 183,
        リーダーライタの機種判定処理でエラーが発生しました = 184,
        コマンドパケットのヘッダ部もしくはフッタ部が不正です = 185,
        指定されたリーダーライタの機器番号が異なります = 186,
        リーダーライタのアクセス権獲得タイムアウトが発生しました = 187,
        トランザクション単位でのアクセス権獲得ロックに失敗しました = 188,
        リーダーライタの機種は未サポートです = 189,
    }

    /// <summary>
    /// Felicaシステムコードの列挙体です。
    /// </summary>
    public enum FelicaSystemCodes : int
    {
        /// <summary>
        /// <br>実運用に使うプログラムで使用するのは推奨されていません。</br>
        /// </summary>
        Any = 0xffff,           // ANY
        /// <summary>
        /// 共通領域
        /// </summary>
        Common = 0xfe00,        // 共通領域
        /// <summary>
        /// サイバネ領域
        /// </summary>
        Cyberne = 0x0003,       // サイバネ領域
        // 使わないと思うので封印しておきます
        //Edy = 0xfe00,           // Edy (=共通領域)
        //Suica = 0x0003,         // Suica (=サイバネ領域)
    }
}